### ISSUE TITLE
my pool is work but website is  not work

### ISSUE THREAD

**Issue by Linge19494492** [bbscoin/bbscoin-pool#2]
i change website config.js ex
var api = "http://pool.bbscoin.xyz:8117"; =>var api = "my ip adrr:8117"

var api_blockexplorer = "https://explorer.bbscoin.xyz";

var poolHost = my ip adrr:8117";

var irc = "irc.freenode.net/#poolhost";

var email = "support@bbscoin.xyz";

var cryptonatorWidget = [];

var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";

var blockchainExplorer = "https://explorer.bbscoin.xyz/?hash={id}#blockchain_block";

var transactionExplorer = "https://explorer.bbscoin.xyz/?hash={id}#blockchain_transaction";

var themeCss = "themes/default-theme.css";

var networkStat = {
    "bbs": [
        ['my ip adrr:8117', 'my ip adrr:8117'],
        ['bbs.pool.pilbeams.net', 'http://bbs.pool.pilbeams.net:8111'],
        ['bbs.pool.ahka.net', 'http://bbs.pool.ahka.net:8115'],
	['bbs.dreampool.info', 'https://bbs.dreampool.info/api/'],
	['cryptoknight.cc/bbs', 'http://78.46.85.142:2778'],
	['bbs.gonspool.com', 'http://bbs.gonspool.com:8117'],
	['pool-marine.ga/bbs', 'http://pool-marine.ga:8028']
    ]
};
but it's erro ERR_CONNECTION_REFUSED   i holp your help

**Comment by Linge19494492** [comment]
my Private Network 172.31.191.102
      Public Network 149.129.129.195
var api = "http://pool.bbscoin.xyz:8117";  which one？

**Comment by randing89** [comment]
Did you start the daemon and wallet seevice?

**Comment by Linge19494492** [comment]
Did you start the daemon and wallet seevice? 
start daemon and wallet  process is running

**Comment by Linge19494492** [comment]
我的daemon和钱包都正常运行，也可以挖矿 ，但是网站浏览器不能运行。老是显示Invalid API call

**Comment by Linge19494492** [comment]
@randing89 已经好了  地址是http://149.129.129.195/

**Comment by swa74** [comment]
http://149.129.129.195:8117/stats - отлично работает

**Comment by randing89** [comment]
Hi. The website is not working http://149.129.129.195/

**Comment by Linge19494492** [comment]
我的服务器还原后就搭不起了。下午再弄。请问服务器配置大概什么配置才带的动？

**Comment by Linge19494492** [comment]
现在搭的是另一个币。下午切过来

**Comment by randing89** [comment]
$5的digital ocean 就够，多加点swap

**Comment by Linge19494492** [comment]
我的是国内的机房

**Comment by Linge19494492** [comment]
上面哪个地址是外国的 vps测试用

**Comment by randing89** [comment]
1g 内存就可以

**Comment by Linge19494492** [comment]
编译就卡死在93%

**Comment by randing89** [comment]
swap不够

**Comment by Linge19494492** [comment]
http://149.129.129.195/  可以了~~~~但是奇怪的分叉后我用的最新的XMRIG 挖矿程序正常 但是不管你官池还是我自己搭的池子都没有算力提交

**Comment by Linge19494492** [comment]
Wrong hashing algorithm

**Comment by randing89** [comment]
更新代码, npm install, 更新bbscoind

**Comment by Linge19494492** [comment]
@randing89 知道原因。。我的服务器在印度 FEE 为0  麻烦能帮我做到你们主页上吗？

**Comment by randing89** [comment]
ok

**Comment by Linge19494492** [comment]
已经可以正常挖矿了～～～。。我也有好的建议，让这个币更有价值～～

**Comment by randing89** [comment]
![image](https://user-images.githubusercontent.com/640557/39503308-10e2a18c-4d7a-11e8-9fe8-106e5c14dc40.png)
Added
