### ISSUE TITLE
npm update fails: WARN This failure might be due to the use of legacy binary "node"

### ISSUE THREAD

**Issue by jbnl** [bbscoin/bbscoin-pool#3]
Hi, I'm using ubuntu 14.04 - all dependencies are installed.
If I use npm update on the latest git clone it gives an error:

WARN This failure might be due to the use of legacy binary "node"

nodejs-legacy is installed, as suggested by the Google search results on this error...

Full error below:

...

../multihashing.cc:579:44: error: no matching function for call to ‘SetMethod(v8::Local<v8::Object>&, const char [6], void (&)(int))’
     NODE_SET_METHOD(exports, "fresh", fresh);
                                            ^
../multihashing.cc:579:44: note: candidate is:
In file included from ../multihashing.cc:1:0:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
 void SetMethod(target_t obj, const char* name,
      ^
/usr/include/nodejs/src/node.h:112:6: note:   template argument deduction/substitution failed:
../multihashing.cc:579:44: note:   cannot convert ‘fresh’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
     NODE_SET_METHOD(exports, "fresh", fresh);
                                            ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-private-field" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-unused-const-variable" [enabled by default]
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory `/bbscoin-pool/node_modules/multi-hashing-bbscoin/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-143-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /bbscoin-pool/node_modules/multi-hashing-bbscoin
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by randing89** [comment]
Your node.js is too old (v0.10.25)
Needs v9.5.0+

**Comment by jbnl** [comment]
If i type node -v in terminal it says:
v10.0.0

**Comment by jbnl** [comment]
Thanks, I've done the above, but now a new error occurs:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for nodejs@^9.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'forknote-pool'
npm ERR! notarget

**Comment by randing89** [comment]
Update your npm first
```
npm install -g npm
```

**Comment by jbnl** [comment]
That gives this error:

npm WARN checkPermissions Missing write access to /root/.nvm/versions/node/v10.0.0/lib/node_modules/npm
npm ERR! path /root/.nvm/versions/node/v10.0.0/lib/node_modules/npm
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/root/.nvm/versions/node/v10.0.0/lib/node_modules/npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by randing89** [comment]
```
sudo npm install -g npm
```

**Comment by jbnl** [comment]
That command ran, but when I do npm update now it says:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for nodejs@^9.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by jbnl** [comment]
I think I've figured out what is happening: 

To use my currently installed pools I have to have nodejs-legacy installed. But that overwrites node to version 0.10.x. I can then start all the pools. Then I can deinstall everything, install latest nodejs via NVM and then compile your pool and run that one. 

If at one point I have to restart a pool then I will have to reinstall all node stuff again to the proper version for it to restart....

**Comment by randing89** [comment]
Something still wrong with your environment... I am not sure what’s going on there

**Comment by jbnl** [comment]
Thanks for the help though mate, appreciate it. 

I will probably have to install my other pools on another pool software. Currently using charnapool that runs only on nodejs-legacy.
