### ISSUE TITLE
npm update failed

### ISSUE THREAD

**Issue by KhmerRun** [bbscoin/bbscoin-pool#4]
Hello, I got error during npm update. Git from today:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lalalolo/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "node" "/home/lalalolo/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lalalolo/pool-bbscoin/bbscoin-pool-20180502/node_modules/multi-hashing-bbscoin
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 2.6.32-042stab127.2
npm ERR! argv "/home/lalalolo/.nvm/v0.10.48/bin/node" "/home/lalalolo/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node@9.11.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node@9.11.0 preinstall script 'node installArchSpecificPackage'.
npm ERR! This is most likely a problem with the node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installArchSpecificPackage
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lalalolo/pool-bbscoin/bbscoin-pool-20180502/npm-debug.log
===========

node version: v0.10.48

**Comment by randing89** [comment]
60个block之后
