### ISSUE TITLE
为什么我的矿池Pending Balance: 469098.80但是没有支付

### ISSUE THREAD

**Issue by Linge19494492** [bbscoin/bbscoin-pool#5]
请问一下 为什么Pending Balance: 469098.80688808 BBS

 Total Paid: 0.00000000 BBS 出现这种情况？

**Comment by randing89** [comment]
不知道。看有没有payment错误吧

**Comment by Linge19494492** [comment]
@randing89 2018-05-02 21:48:03 Error with send_transaction RPC request to wallet daemon {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8070}
2018-05-02 21:48:03 Payments failinged to send to {"amount":17714700000000,"address":"fyT4qhFMDZTBLpmhatqFzD43MEV4B1J6b96S637dxSmAM7i3VkuAi3X89ESmWJYGYzCB1V9UA6bAB7USpn4q1LRF34Mc7Y8DJ"} { amount: 9701100000000,
  address: 'fyTTBdEyg6HYquvBN65TQ7h3x3UA1VmrWiYdGKNNpdEEWYTbATVHkU6bJxxnDYGB5ahwjyMaCUT2Aig9vBLfTuGP392yn9cJp' }

**Comment by Linge19494492** [comment]
@randing89 需不需要设置钱包密码？

**Comment by Linge19494492** [comment]
@randing89 是不是因为钱包密码问题？

**Comment by Linge19494492** [comment]
@randing89 2018-05-03 13:48:03 Error with send_transaction RPC request to wallet daemon {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8070}
2018-05-03 13:48:03 Payments failinged to send to {"amount":2978700000000,"address":"fyTSEryZMqKBnrEYfVcGz539G1cphM6GTXheExAtkTteMeoiCLFW5PA4i6LjryBM3rMyhQVwScgGyRFPxpZP7Vhu2bPs92eAu"} { amount: 878500000000,
  address: 'fySRCCeGVE8R5RFQJePW7R3igi2DvUdKMj9geNNc5cWfBBANN5pixXt6pkR7fnPhcHgB5XnK889Y7MRBEzHBbtD42PvFmBXoB' } { amount: 55999000000000,
  address: 'fyTTBdEyg6HYquvBN65TQ7h3x3UA1VmrWiYdGKNNpdEEWYTbATVHkU6bJxxnDYGB5ahwjyMaCUT2Aig9vBLfTuGP392yn9cJp' } { amount: 4457400000000,
  address: 'fyU3NmJqPRba2pfVeGji4gCiU7c5ttKw2NLAs1guNzJ83TysF5raQpiAGoQAfeKUnVBsi6G8qLu6vej12RWnuMTn2tuHrFg6v' } { amount: 46909800000000,
  address: 'fyT4qhFMDZTBLpmhatqFzD43MEV4B1J6b96S637dxSmAM7i3VkuAi3X89ESmWJYGYzCB1V9UA6bAB7USpn4q1LRF34Mc7Y8DJ' }

**Comment by Linge19494492** [comment]
@randing89 我钱包程序是打开的~~~

**Comment by randing89** [comment]
你启动walletd了吗？walletd  -w /path/to/wallet/file.wallet --daemon-port=21204

**Comment by randing89** [comment]
有密码要walletd -w /path/to/wallet/file.wallet -p password --daemon-port=21204

**Comment by Linge19494492** [comment]
@randing89 估计是这个原因 谢谢了

**Comment by Linge19494492** [comment]
@randing89 walletd -w /path/to/wallet/file.wallet -p password --daemon-port=21204 用这个命令后 会新建一个用户 原来的用户会BACKUP 是不是参数不对

**Comment by randing89** [comment]
发一下log

**Comment by Linge19494492** [comment]
2018-May-03 14:28:52.626589 INFO    Loading wallet
2018-May-03 14:28:52.626680 INFO    Loading container...
2018-May-03 14:28:52.662115 INFO    Consumer added, consumer 0x015da100, count 1
2018-May-03 14:28:52.666180 INFO    Saving...
2018-May-03 14:28:52.666272 INFO    Saved
2018-May-03 14:28:52.672933 INFO    Wallet file converted! Previous version: "linge1.wallet.backup"
2018-May-03 14:28:52.673038 INFO    Starting...
2018-May-03 14:28:52.673152 INFO    Container loaded, view public key 2206227045ccf27cd72299a12cd46a4214838eb2e956cb1721cb1452806dde3b, wallet count 1, actual balance 0.00000000, pending balance 0.00000000
2018-May-03 14:28:52.673435 INFO    Wallet loading is finished.
2018-May-03 14:28:52.673570 INFO    Removing outdated pool transactions...
2018-May-03 14:28:52.711085 INFO    Outdated pool transactions processed
2018-May-03 14:29:00.370427 INFO    Wallet balance updated, address fyTXciQrByX3qpjPZfwECHXF4Ta2GDkF2JTY6VVdcfCRaKbqfKueVABhZSB5sRJ1BhJmqYQVoYrE9ayEPhusii8C2ufYEESoh, actual 278733.37322432, pending 278680.31507525
2018-May-03 14:29:00.370630 INFO    Container balance updated, actual 278733.37322432, pending 278680.31507525
2018-May-03 14:29:00.843384 INFO    Wallet balance updated, address fyTXciQrByX3qpjPZfwECHXF4Ta2GDkF2JTY6VVdcfCRaKbqfKueVABhZSB5sRJ1BhJmqYQVoYrE9ayEPhusii8C2ufYEESoh, actual 557413.68829957, pending 0.00000000
2018-May-03 14:29:00.843578 INFO    Container balance updated, actual 557413.68829957, pending 0.00000000
2018-May-03 14:29:02.146457 INFO    Wallet balance updated, address fyTXciQrByX3qpjPZfwECHXF4Ta2GDkF2JTY6VVdcfCRaKbqfKueVABhZSB5sRJ1BhJmqYQVoYrE9ayEPhusii8C2ufYEESoh, actual 1114439.52713319, pending 0.00000000
2018-May-03 14:29:02.146667 INFO    Container balance updated, actual 1114439.52713319, pending 0.00000000

**Comment by randing89** [comment]
没问题

**Comment by Linge19494492** [comment]
老是把原来的钱包备份  然后新建一个同名字的钱包

**Comment by Linge19494492** [comment]
@randing89 到账了~~~

**Comment by Linge19494492** [comment]
@randing89 有没有联系方式~~有些平台可以免费上币~~~

**Comment by Linge19494492** [comment]
免 费 上 币

**Comment by randing89** [comment]
请不要把这里当聊天室

**Comment by randing89** [comment]
qq: 8247777 telegram: https://t.me/bbscoin_cn

**Comment by Linge19494492** [comment]
@randing89 能不能单独加Q 我周围我拉了20多个人在玩这个。希望一起把项目搞起来。2849254402
看到BCN 这么垃圾的项目都做起来。。我们也可以的~~~我想合作
